### ISSUE TITLE
Floating-Point instructions support

### ISSUE THREAD

**Issue by arkup** [wargio/libvle#12]
Hi, would be great if you could implement floating-point instructions support..seems only IDA, objdump can disasm the FPU instructions e.g.

```
10 60 02 D1     efscfsi   r3, r0
13 a3 02 c9 	efsdiv  r29,r3,r0

```
even the NSA baby (Ghidra 9.0.1) failed on this :(

**Comment by wargio** [comment]
https://www.nxp.com/docs/en/reference-manual/e200z760RM.pdf from page 171

**Comment by wargio** [comment]
Added with commit https://github.com/wargio/libvle/commit/a44abdd73b2ed567d1ec169fb124e8edb815cf2b

```
efscfh
efscfsf
efscfsi
efscfuf
efscfui
efscmpgt
efscmpeq
efscmplt
efsctsi
efsctsf
efsctsi
efsctsiz
efsctuf
efsctui
efsctuiz
efsdiv
efsmadd
efsmax
efsmin
efsmsub
efsmul
efsnabs
efsneg
efsnmadd
efsnmsub
efssqrt
efssub
efststeq
efststgt
efststlt
```

**Comment by wargio** [comment]
all vector maths are still missing

**Comment by arkup** [comment]
nice thx! I will test it tomorrow
EDIT: seems to be working fine
