### ISSUE TITLE
Clarify Licensing

### ISSUE THREAD

**Issue by ehntoo** [wargio/libvle#4]
Hi!
I was considering basing a VLE architecture plugin for Binary Ninja around this library, but first I'd like to get some clarification about what software license I'd be subject to.

Could you add a software license to the repo? https://help.github.com/articles/licensing-a-repository/
Thanks!

*edit*
I see there's an LGPL reference at the top of vle_internal.h. I'd be happy to put together a pull request to include the LGPL in the project if that license was your intended one. :)

**Comment by wargio** [comment]
Oh, right. I forgot that. Yes, if you want to make a PR, I'm ok.

**Comment by wargio** [comment]
i've added the license.
