### ISSUE TITLE
Incorrect disassembly

### ISSUE THREAD

**Issue by arkup** [wargio/libvle#5]
thanks for this lib. I started playing with ppc32 arch and I noticed incorrect disassembly of instruction:
```
7A 20 FF F8                   e_bgectr cr0 0xfffffff8
```
seems it should be **e_bdnz**  at least that's what IDA prints (other tools like Ghidra failed to disasm this instr)
```
7A 20 FF F8                 e_bdnz    loc_4028E
```

**Comment by wargio** [comment]
oh. i'll check via objdump

**Comment by wargio** [comment]
![image](https://user-images.githubusercontent.com/561184/53951218-42d1d800-40ce-11e9-9100-90add6768bdf.png)
Mask: 0x7A20FFFE

**Comment by wargio** [comment]
IDA is correct. i'll patch it asap

**Comment by wargio** [comment]
fixed in https://github.com/wargio/libvle/commit/4d888ffbe7d0a8add0fb0ff528fea92529b8a8b0
