### ISSUE TITLE
Cant disasm e_lbz      r23 ,0x60 (r4)

### ISSUE THREAD

**Issue by arkup** [wargio/libvle#8]
hi, seems it's not possible to disasm bytes 32  e4  00  60

from IDA
```
.text:00000000  32 E4 00 60                 e_lbz     r23, 0x60(r4)
```

**Comment by arkup** [comment]
another case for testing
```
        .text:00000000 33  e3  00  11    e_lbz      r31 ,0x11 (r3)
```

**Comment by wargio** [comment]
fixed with https://github.com/wargio/libvle/commit/dbb4be7dada3ec668bb4e6afe6c769b1dd21ab48
