### ISSUE TITLE
Cant disasm e_lhz r28 ,0x58 (r6)

### ISSUE THREAD

**Issue by arkup** [wargio/libvle#9]
hi, seems it's not possible to disasm bytes ```5b  86  00  58```

from Ghidra I get:
```
 00000038 5b  86  00  58    e_lhz      r28 ,0x58 (r6)
```

**Comment by wargio** [comment]
fixed with https://github.com/wargio/libvle/commit/dbb4be7dada3ec668bb4e6afe6c769b1dd21ab48
